version: "3.9"

services:
  appbord:
    image: ghcr.io/irhm/appbord:latest
    container_name: appbord
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - "3000:3000"
    restart: unless-stopped
